"""Compose Polygon-shaped statement sections and final display examples."""

import json
import re
from decimal import Decimal
from pathlib import Path
from unicodedata import east_asian_width


DIRECTIVE = re.compile(r"\\polygonstatement\{([A-Z]+)\}\{([^{}]+)\}")
EXAMPLE = re.compile(r"example\.(\d+)(\.a)?")
SECTIONS = (("input", "InputSection"), ("output", "OutputSection"),
            ("interaction", "InteractionSection"), ("scoring", "ScoringSection"))


def text_content(path: Path) -> str:
    return re.sub(r"(?<!\\)%[^\n]*", "", path.read_text(encoding="utf-8-sig")).strip()


def tex_path(path: Path) -> str:
    value = path.as_posix()
    if any(character in value for character in '%#{}\\"\n\r'):
        raise ValueError(f"Unsupported TeX path: {path}")
    return value


def example_files(sections: Path) -> list[tuple[Path, Path]]:
    pairs = {}
    for path in sections.iterdir():
        match = EXAMPLE.fullmatch(path.name)
        if match is None or not path.is_file():
            continue
        number = int(match[1])
        if number < 1:
            raise ValueError(f"Example numbers must be positive: {path}")
        side = "output" if match[2] else "input"
        pair = pairs.setdefault(number, {})
        if side in pair:
            raise ValueError(f"Duplicate example number: {path}")
        pair[side] = path
    result = []
    for number, pair in sorted(pairs.items()):
        if set(pair) != {"input", "output"}:
            raise ValueError(f"Example {number} needs both input and output files: {sections}")
        result.append((pair["input"], pair["output"]))
    return result


def sample_layout(mode: str, input_file: Path, output_file: Path) -> str:
    if mode not in ("auto", "paired", "stacked"):
        raise ValueError(f"Unknown sampleLayout: {mode}")
    if mode != "auto":
        return mode
    for path in (input_file, output_file):
        lines = path.read_text(encoding="utf-8-sig").splitlines()
        if len(lines) > 28 or any(sum(2 if east_asian_width(c) in "WF" else 1
                                   for c in line.expandtabs(8)) > 65 for line in lines):
            return "stacked"
    return "paired"


def render_fragment(letter: str, sections: Path, info: dict) -> str:
    for name in ("name", "legend", "input", "output"):
        if not (sections / f"{name}.tex").is_file():
            raise ValueError(f"Missing statement section: {sections / (name + '.tex')}")
    title = text_content(sections / "name.tex")
    if not title or "\n" in title or "\r" in title:
        raise ValueError(f"name.tex must contain a nonempty single-line TeX title: {sections}")
    time = info.get("timeLimit")
    memory = info.get("memoryLimit")
    for key, value in (("timeLimit", time), ("memoryLimit", memory)):
        if value is not None and (type(value) is not int or value <= 0):
            raise ValueError(f"{key} must be a positive integer or null")
    seconds = "" if time is None else format(Decimal(time) / 1000, "f")
    if "." in seconds:
        seconds = seconds.rstrip("0").rstrip(".")
    language = info.get("language")
    if not isinstance(language, str) or sections.name != language:
        raise ValueError("Statement directory must match statement.json language")
    if info.get("interactive") and not (sections / "interaction.tex").is_file():
        raise ValueError("Interactive statements need interaction.tex")
    lines = ["% Generated by kgupc-toolkit; edit the statement sections instead.",
             f"\\problemheader{{{letter}}}{{{title}}}",
             f"\\problemlimits{{{seconds}}}{{{memory if memory is not None else ''}}}",
             f"\\import{{{tex_path(sections)}/}}{{legend.tex}}", ""]
    # Record even empty optional fields in .fls for editor dependency watching.
    dependencies = [sections / f"{name}.tex" for name in
                    ("name", "legend", "input", "output", "notes", "interaction", "scoring")]
    lines[1:1] = [f"\\StatementSourceDependency{{{tex_path(path)}}}"
                  for path in dependencies if path.is_file()]
    for name, heading in SECTIONS:
        source = sections / f"{name}.tex"
        if source.is_file() and text_content(source):
            lines.extend([f"\\{heading}",
                          f"\\import{{{tex_path(sections)}/}}{{{name}.tex}}", ""])
    examples = example_files(sections)
    mode = info.get("sampleLayout", "auto")
    if mode not in ("auto", "paired", "stacked"):
        raise ValueError(f"Unknown sampleLayout: {mode}")
    if examples:
        lines.extend(["\\SampleSection", "\\nointerlineskip"])
        for number, (input_file, output_file) in enumerate(examples, 1):
            command = "SampleFilePair" if sample_layout(mode, input_file, output_file) == "paired" else "SampleFileStack"
            lines.append(f"\\{command}{{{number}}}{{{tex_path(input_file)}}}{{{tex_path(output_file)}}}")
    notes = sections / "notes.tex"
    if notes.is_file() and text_content(notes):
        lines.extend(["", "\\ExplanationSection",
                      f"\\import{{{tex_path(sections)}/}}{{notes.tex}}"])
    # tutorial.tex contains a solution and deliberately never enters a problem PDF.
    return "\n".join(lines) + "\n"


def prepare_statements(directory: Path, entries: list[tuple[str, str]]) -> None:
    planned = []
    for letter, filename in entries:
        problem = directory / letter
        wrapper = problem / filename
        content = text_content(wrapper)
        match = DIRECTIVE.fullmatch(content)
        if match is None:
            if "\\polygonstatement" in content:
                raise ValueError(f"Expected only \\polygonstatement{{{letter}}}{{statement-sections/<language>}}: {wrapper}")
            continue  # Existing monolithic statements still work.
        if match[1] != letter:
            raise ValueError(f"Statement letter differs from problem-list.tex: {wrapper}")
        sections = (problem / match[2]).resolve()
        if not sections.is_relative_to(problem.resolve()) or not sections.is_dir():
            raise ValueError(f"Invalid statement directory: {sections}")
        info = json.loads((problem / "statement.json").read_text(encoding="utf-8-sig"))
        dependency = f"\\StatementSourceDependency{{{tex_path(problem.resolve() / 'statement.json')}}}\n"
        planned.append((directory / "build" / "statements" / f"{letter}.tex",
                        dependency + render_fragment(letter, sections, info)))
    for path, content in planned:
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8", newline="\n")
